server:
  port: 12011
spring:
  application:
    name: microservice-shiro
  jpa:
    database: MYSQL
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties: 
      hibernate: 
        dialect : org.hibernate.dialect.MySQL5Dialect
  datasource:                     
    url: jdbc:mysql://127.0.0.1:3306/microservice_system?useUnicode=true&amp;characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root  
    password: root
  redis: 
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    pool: 
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
  thymeleaf: 
        cache: false
        prefix: classpath:/static/html/shiro/
        suffix: .html
        mode: HTML5
        encoding: UTF-8
        content-type: text/html    
logging: 
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    #com.itmuch.youran.persistence: ERROR
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/ 
  instance:
    preferIpAddress: true