server:
  port: 8081
spring:
  application:
    name: microservice-demo-web    # 项目名称尽量用小写
#  jpa:
#    generate-ddl: false
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#  datasource:                           # 指定数据源
#    platform: h2                        # 指定数据源类型
#    schema: classpath:schema.sql        # 指定h2数据库的建表脚本
#    data: classpath:data.sql            # 指定h2数据库的insert脚本
#  datasource:                           # 指定数据源
#    url: jdbc:mysql://127.0.0.1:3306/microservice_demo?useUnicode=true&characterEncoding=utf8
#    driverClassName: com.mysql.jdbc.Driver
#    username: root  
#    password: root 

  rabbitmq:                               # 指定rabbitmq源
     addresses: 127.0.0.1:5672
     username: springcloud
     password: springcloud
     virtual-host: / 
    
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true