server:
  port: 12000
spring:
  application:
    name: microservice-system    
  jpa: 
    database: MYSQL
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties: 
      hibernate: 
        dialect : org.hibernate.dialect.MySQL5Dialect
  datasource:                       
    url: jdbc:mysql://127.0.0.1:3306/springcloud1-microservice?useUnicode=true&amp;characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root  
    password: root
#  redis: 
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    password: 123456
#    pool: 
#      max-active: 8
#      max-wait: -1
#      max-idle: 8
#      min-idle: 0
#    timeout: 0
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    #com.itmuch.youran.persistence: ERROR
eureka:
  client:
    #healthcheck: 
     # enabled: true
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}